package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

type AutoGenerated struct {
	Slip struct {
		ID     int    `json:"id"`
		Advice string `json:"advice"`
	} `json:"slip"`
}

func main() {

	req, err := http.Get("https://api.adviceslip.com/advice")

	if err != nil {
		fmt.Println(err)
	}

	defer req.Body.Close()

	res, err := io.ReadAll(req.Body)
	if err != nil {
		fmt.Println(err)
	}

	var resposta AutoGenerated

	json.Unmarshal(res, &resposta)

	fmt.Println(resposta.Slip.Advice)

}
